SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;
DROP TABLE "USERS" CASCADE CONSTRAINTS;
DROP TABLE "ADDRESS" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "ANSWER_VOTER" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "CATEGORY_ITEM" CASCADE CONSTRAINTS;
DROP TABLE "DELIVERY" CASCADE CONSTRAINTS;
DROP TABLE "EXCHANGE" CASCADE CONSTRAINTS;
DROP TABLE "ITEM" CASCADE CONSTRAINTS;
DROP TABLE "ITEM_IMAGE" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_ITEM" CASCADE CONSTRAINTS;
DROP TABLE "ORDERS" CASCADE CONSTRAINTS;
DROP TABLE "QUESTION_VOTER" CASCADE CONSTRAINTS;
DROP TABLE "REFUND" CASCADE CONSTRAINTS;
DROP TABLE "SITE_USER" CASCADE CONSTRAINTS;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUTHORITIES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NOTICE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE REFUND';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EXCHANGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ITEM_IMAGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CART';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BOARD';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ORDERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ITEM';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORY';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADDRESS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USER_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BOARD_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE NOTICE_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ORDER_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ITEM_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE EXCHANGE_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE REFUND_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ITEM_IMAGE_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE CART_NO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;

CREATE TABLE USERS
(
    no	           number		            NOT NULL,
    address_no     number		            NOT NULL,
    detail_address varchar2(500)            NOT NULL,
    id	           varchar2(20)		        NOT NULL,
    password       varchar2(300)		    NOT NULL,
    name	       varchar2(10)		        NOT NULL,
    email	       varchar2(80)		        NOT NULL,
    phone	       varchar2(11)		        NOT NULL,
    reg_date       date    DEFAULT SYSDATE	NOT NULL,
    del_flag       char(1) DEFAULT 'N'	    NOT NULL
);

CREATE TABLE AUTHORITIES
(
    user_no	  number		                  NOT NULL,
    authority varchar(50) DEFAULT 'ROLE_USER' NOT NULL
);

CREATE TABLE ADDRESS
(
    no	         number       NOT NULL,
    sido_name    varchar2(30) NULL,
    sigungu_name varchar2(30) NULL,
    dong_name	 varchar2(30) NULL
);

CREATE TABLE BOARD
(
    no	     number		                    NOT NULL,
    user_no	 number		                    NOT NULL,
    title	 varchar2(300)		            NOT NULL,
    content	 varchar2(3000)	DEFAULT SYSDATE	NOT NULL,
    reg_date date		                    NOT NULL,
    hit	     number	 DEFAULT 0              NOT NULL,
    del_flag char(1) DEFAULT 'N'	        NOT NULL
);

CREATE TABLE NOTICE
(
    no	     number		NOT NULL,
    board_no number		NOT NULL
);

CREATE TABLE ORDERS
(
    no	     number		          NOT NULL,
    user_no	 number		          NOT NULL,
    item_no	 number		          NOT NULL,
    amount	 number		          NOT NULL,
    status	 number		          NOT NULL,
    reg_date date DEFAULT SYSDATE NOT NULL
);

CREATE TABLE ITEM
(
    no          number		         NOT NULL,
    category_no	number		         NOT NULL,
    name	    varchar2(30)		 NOT NULL,
    quantity	number		         NOT NULL,
    price	    number		         NOT NULL,
    content	    varchar2(2000)		 NOT NULL,
    reg_date	date DEFAULT SYSDATE NOT NULL
);

CREATE TABLE CATEGORY
(
    no	 number		  NOT NULL,
    name varchar2(50) NOT NULL
);

CREATE TABLE EXCHANGE
(
    no	          number		        NOT NULL,
    order_no	  number		        NOT NULL,
    reg_date	  date DEFAULT SYSDATE	NOT NULL,
    exchange_date date		            NULL
);

CREATE TABLE REFUND
(
    no	        number NOT NULL,
    order_no	number NOT NULL,
    reg_date	date   NOT NULL,
    refund_date	date   NULL
);

CREATE TABLE ITEM_IMAGE
(
    no	     number		   NOT NULL,
    item_no	 number		   NOT NULL,
    filename varchar2(150) NOT NULL,
    filepath varchar2(300) NOT NULL
);

CREATE TABLE CART
(
    no	     number	NOT NULL,
    user_no	 number	NOT NULL,
    item_no	 number	NOT NULL,
    quantity number NOT NULL
);

CREATE SEQUENCE USER_NO_SEQ;
CREATE SEQUENCE BOARD_NO_SEQ;
CREATE SEQUENCE NOTICE_NO_SEQ;
CREATE SEQUENCE ORDER_NO_SEQ;
CREATE SEQUENCE ITEM_NO_SEQ;
CREATE SEQUENCE EXCHANGE_NO_SEQ;
CREATE SEQUENCE REFUND_NO_SEQ;
CREATE SEQUENCE ITEM_IMAGE_NO_SEQ;
CREATE SEQUENCE CART_NO_SEQ;


ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (no);
ALTER TABLE ADDRESS ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (no);
ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (no);
ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (no);
ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDER PRIMARY KEY (no);
ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (no);
ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (no);
ALTER TABLE EXCHANGE ADD CONSTRAINT PK_EXCHANGE PRIMARY KEY (no);
ALTER TABLE REFUND ADD CONSTRAINT PK_REFUND PRIMARY KEY (no);
ALTER TABLE ITEM_IMAGE ADD CONSTRAINT PK_ITEM_IMAGE PRIMARY KEY (no);
ALTER TABLE CART ADD CONSTRAINT PK_CART PRIMARY KEY (no);

ALTER TABLE USERS
    ADD CONSTRAINT FK_ADDRESS_TO_USER_1 FOREIGN KEY (address_no)
    REFERENCES ADDRESS (no);

ALTER TABLE AUTHORITIES
    ADD CONSTRAINT FK_USER_TO_AUTHORITIES_1 FOREIGN KEY (user_no)
    REFERENCES USERS (no);

ALTER TABLE BOARD
    ADD CONSTRAINT FK_USER_TO_BOARD_1 FOREIGN KEY (user_no)
    REFERENCES USERS (no);

ALTER TABLE NOTICE
    ADD CONSTRAINT FK_BOARD_TO_NOTICE_1 FOREIGN KEY (board_no)
    REFERENCES BOARD (no);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_USER_TO_ORDER_1 FOREIGN KEY (user_no)
    REFERENCES USERS (no);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ITEM_TO_ORDER_1 FOREIGN KEY (item_no)
    REFERENCES ITEM (no);

ALTER TABLE ITEM
    ADD CONSTRAINT FK_CATEGORY_TO_ITEM_1 FOREIGN KEY (category_no)
    REFERENCES CATEGORY (no);

ALTER TABLE EXCHANGE
    ADD CONSTRAINT FK_ORDER_TO_EXCHANGE_1 FOREIGN KEY (order_no)
    REFERENCES ORDERS (no);

ALTER TABLE REFUND
    ADD CONSTRAINT FK_ORDER_TO_REFUND_1 FOREIGN KEY (order_no)
    REFERENCES ORDERS (no);

ALTER TABLE ITEM_IMAGE
    ADD CONSTRAINT FK_ITEM_TO_ITEM_IMAGE_1 FOREIGN KEY (item_no)
    REFERENCES ITEM (no);

ALTER TABLE CART
    ADD CONSTRAINT FK_USER_TO_CART_1 FOREIGN KEY (user_no)
    REFERENCES USERS (no);

ALTER TABLE CART
    ADD CONSTRAINT FK_ITEM_TO_CART_1 FOREIGN KEY (item_no)
    REFERENCES ITEM (no);

